[package]
name = "rustlab"
version = "2.3.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.5"
crossbeam="0.8.3"
